### ISSUE TITLE
Error in tests 

### ISSUE THREAD

**Issue by gabriele-bani** [mmxgn/spacy-clausie#2]
Hi, when running the tests or the sample code provided in the readme, i get TypeError: Argument 'doc' has incorrect type (expected spacy.tokens.doc.Doc, got spacy.tokens.span.Span).

Is there any specific reason for this?

The installation happened as you described, with the exception that i had to install `lemminflect`manually with pip.

**Comment by gabriele-bani** [comment]
Hi, i found out that the problem was that I did not have the correct version of Spacy installed :)

**Comment by mmxgn** [comment]
Hi, 

Sorry for my delay.

However, It's nice to see that you solved it :)
