### ISSUE TITLE
Inconsistent data types

### ISSUE THREAD

**Issue by Christopher-Thornton** [mmxgn/spacy-clausie#4]
On line 256 of `claucy.py`, one of the tuple items is a string:
`propositions.append((subj, "is", c))`

This data type is incompatible with the `_convert_clauses_to_text` function as a spacy doc object is expected.
I wrote a workaround  below:
```
def _convert_clauses_to_text(propositions, inflect, capitalize):
    proposition_texts = []
    for proposition in propositions:
        span_texts = []
        for span in proposition:
            # TODO: Change workaround to permit inflections
            if isinstance(span, str):  # e.g. 'is'
                span_texts.append(span)
            else:
                token_texts = []
                for token in span:
                    token_texts.append(inflect_token(token, inflect))
                span_texts.append(" ".join(token_texts))

        proposition_texts.append(" ".join(span_texts))

    if capitalize:  # Capitalize and add a full stop.
        proposition_texts = [text.capitalize() + "." for text in proposition_texts]

    return proposition_texts
```
To permit different inflections of "is" (i.e. was), the string could be converted to a spacy doc object or changes could be made to the `_convert_clauses_to_text `function.

**Comment by mmxgn** [comment]
Hi,

Thanks for your efforts.

My only concern with making a single "is" as a doc object is that it is disconnected from the source sentence. In our case, it doesn't seem to matter.

What's your idea on this:

If the inflection is different from a default value, then:

- Wrap "is" as a doc object
- Inflect, but also include a warning that this is a hacky workaround.

Else keep "is" as a string object.
