### ISSUE TITLE
Argument 'doc' has incorrect type

### ISSUE THREAD

**Issue by xiaohy9** [mmxgn/spacy-clausie#9]
I tried to run the following example code, but got the following error at doc=nlp() line. 
TypeError: Argument 'doc' has incorrect type (expected spacy.tokens.doc.Doc, got spacy.tokens.span.Span)

My spacy version is 2.2.4. git clone the latest spacy-clausie. 
Please help. Thanks.

```
import spacy                                                                                                                                               
import claucy       

nlp = spacy.load("en_core_web_sm")
claucy.add_to_pipe(nlp)

doc = nlp("AE died in Princeton in 1955.")
print(doc._.clauses)
propositions = doc._.clauses[0].to_propositions(as_text=True)                                                                                               
propositions

```

**Comment by mmxgn** [comment]
Hi

Thank you for your interest in claucy.

The minimum requirement is Spacy 2.3.0 (but less than 3.0.0 currently). Could you update your spacy with 

```
pip install "spacy>=2.3.0,<3.0.0"
```
and try again?

**Comment by xiaohy9** [comment]
Thanks for the response!
I’ve installed the spacy 2.3.7, and the error is gone now. however, I saw some warning message:
WARNING:root:`inflect' argument is ignored when `as_text==False'

It is annoying to see hundreds of them when I process a large number of sentences. It would be much better not to have them.

**Comment by mmxgn** [comment]
Hi,

For the warnings I suggest you call `to_propositions`  with the argument `inflect=None` (I should probably add documentation there that says so).

**Comment by mmxgn** [comment]
Hello again,

Could you close this issue if the above issues have been resolved for you? If you have more questions you are welcome to open new issues :)

**Comment by mmxgn** [comment]
Closing this since it seems to be resolved. Feel free to reopen it if it hasn't.
